language: python
matrix:
  include:
  - os: linux
    dist: trusty
    python: '2.7'
    env: TOX_ENV=py27
  - os: linux
    dist: trusty
    python: '2.7'
    env: TOX_ENV=pep8
  - os: linux
    dist: trusty
    python: '3.5'
    env: TOX_ENV=py35
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install tox codecov coverage
script:
  - tox -e TOX_ENV
after_success:
  - coverage combine
  - codecov
branches:
  only:
    - master
