language: python
env:
  - TOX_ENV=py27
  - TOX_ENV=pep8
  - TOX_ENV=py35
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install tox codecov coverage
script:
  - tox -e $TOX_ENV
after_success:
  - coverage combine
  - codecov
branches:
  only:
    - master
